### ISSUE TITLE
Error when adding text to end of line

### ISSUE THREAD

**Issue by Krispian** [gorhill/PHP-FineDiff#12]
Hello! When we add the text to the end of the line, it is captured with the last word. http://i.imgur.com/Fo9i0Ys.png  Any idea how to avoid it?

**Comment by gorhill** [comment]
Use character-level granularity. The behavior you are seeing is because by default the text is segmented into chunks of [contiguous non-blank characters followed by contiguous blank characters]. Be aware that the higher the grannularity, the more work for the CPU.
