### ISSUE TITLE
Excluding html tags while showing copied content

### ISSUE THREAD

**Issue by varinder61** [gorhill/PHP-FineDiff#13]
Hello, I am using php fine diff for showing duplicate content within websites but i am facing one problem which is that it includes html tag aatributes values also while comparing content. As i want character level granularity for this and when i am doing so the problem is that it will insert copy tag within html elements also.

I have attached the screenshot of problem ; its inserting copy tag in title attribute of anchor tag.
![screenshot](https://f.cloud.github.com/assets/5592688/1251993/0be1d0de-2b3f-11e3-8c56-85f84332d5fa.JPG)
Awaiting for your reply.

**Comment by gorhill** [comment]
FineDiff is agnostic when it comes to text, it does not try to understand and do fancy stuff with the text content. So it doesn't treat specially text which is HTML. It just plainly compute the smallest diff between two strings, regardless of their meaning to something else. So this `<copy>` tag you are seeing comes from somewhere else, nowhere in finediff.php is there code to insert such tag.

**Comment by jamienk** [comment]
I'd like this too -- the ability to skip HTML tags. I'm thinking I'd need some kind of custom delimiter, but that doesn't seem right, as those are all single characters.

Any advice on how to get started adding this option?

**Comment by gorhill** [comment]
@jamienk That's no the right issue for your question (looks like I forgot to close this issue -- I was waiting for confirmation from @varinder61 ).

In any case, as said, FineDiff is low-level, it doesn'care about what the bytes it "diffes" are about. So if you want to diff two HTML documents, you will have to first diff the document structures (diffing two tree structures, which is not what FineDiff is about), than for each text node in your trees which are matched, you would be diffing the text content using FineDiff.
