### ISSUE TITLE
renderFromOpcodes should return Text

### ISSUE THREAD

**Issue by asnyder** [gorhill/PHP-FineDiff#15]
For whatever reason renderFromOpcodes takes in a callback which we're supposed to handle, however you don't process any return from the callback making it such that the function will always return NULL. As such one needs to create a global shared variable, set it to blank beforehand, call renderFromOpCodes with callback, modify global string in callback and then use global string afterwards. Wouldn't it be more in line with modern development practices and the rest of the library to have the renderFromOpcodes allow the callback to return a string which renderFromOpcodes concats and returns?

**Comment by gorhill** [comment]
You can use a [closure](http://www.php.net/manual/en/functions.anonymous.php), no need to rely strictly on a global variable.

If you see the output of `renderFromOpcodes` as a stream, the callback makes sense: it's there so the caller does whatever it wants with the output stream, which he might just want to output to `stdout`.

Forcing `renderFromOpcodes` to concat into an intermediate in-memory string instance introduces an overhead to the detriment of such a simple cases. So the preferred approach has been to not assume the caller may be interested in the output string as a whole, and so minimize overhead by letting the callers assemble the way they see fit with no assumptions.

**Comment by asnyder** [comment]
Your right, except my handler function is in another class and it needs to access the buffer too. That said, it is a function and functions should return something, especially since it's  billed as a replacement to the other render functions that do return. Anyway, it's working for me now, but I can see it being confusing to others.
