### ISSUE TITLE
Incorrect double encoding of some special HTML characters

### ISSUE THREAD

**Issue by 1emming** [gorhill/PHP-FineDiff#16]
Hello Raymond,

Thank you writing and sharing FineDiff! I've been using it in several projects now. I would like to ask you something about how to resolve some situations I've run into.

The first one has to do when rendering to HTML. In some cases the result is double encoded. I've made a little test to explain how I use the library. (running on 5.3.3-7+squeeze19)

Test 1:

```
require_once __DIR__ . '/../classes/external/finediff/finediff.php';

$granularities = 1;
$from = "a b c";
$to = "a ’ a";

$diff_ops = \FineDiff::getDiffOpcodes($from, $to, $granularities);
$result = \FineDiff::renderDiffToHTMLFromOpcodes($from, $diff_ops);

header('HTTP/1.1 200 OK');
header('Content-type: text/html; charset=UTF-8');
echo $result;
die;
```

This results into:
    a <del>b</del><ins>&amp;rsquo;</ins> <del>c</del><ins>a</ins>
    (a b&rsquo; ca)

After removing the second htmlentities call and adding the UTF-8 hint in finediff (line 684) the result is what I expected:
    a <del>b</del><ins>&rsquo;</ins> <del>c</del><ins>a</ins>
    (a b’ ca)

I think the problem is a combination of character encoding and some
HTML special characters like '’', '†', etc.

I'm not sure why the second `htmlentities` call is needed. 
You must have done it for a reason so I hesitate to remove it from our codebase just yet.

The second test is with UTF-8. I've read your FAQ and did a few tests. 
Test 2:

```
require_once __DIR__ . '/../classes/external/finediff/finediff.php';

$granularities = 1;
$from = "a b a";
$to = "a 中 a";

$from = mb_convert_encoding($from, 'HTML-ENTITIES', 'UTF-8');
$to = mb_convert_encoding($to, 'HTML-ENTITIES', 'UTF-8');

$diff_ops = \FineDiff::getDiffOpcodes($from, $to, $granularities);
$result = \FineDiff::renderDiffToHTMLFromOpcodes($from, $diff_ops);

header('HTTP/1.1 200 OK');
header('Content-type: text/html; charset=UTF-8');
echo $result;
die;
```

Result with calling: mb_conver_encoding:
    a b&amp;#20013; a

Result without calling: mb_conver_encoding:
    a b&auml;&cedil;&shy; a

Result calling with: mb_convert_encoding($from, "UTF-8");
    a b&Atilde;&curren;&Acirc;&cedil;&Acirc;&shy; a

When modifying the `htmlentities` call in finediff.php the codes works as expected without doing any conversion on the `from` and `to` strings.
a <del>b</del><ins>&amp;rsquo;</ins> <del>c</del><ins>a</ins>
(a b中 a)

Thank you for reading my questions, I hope you have some time to point me in
a direction to work out these two use-cases.

Best regards,
Seb

PS.
Thought to let you know that on GitHub (https://github.com/gorhill/PHP-FineDiff) the link within your Copyright statement (http://raymondhill.net/blog/?p=441) doesn't seem to work any more.

**Comment by gorhill** [comment]
@1emming I wish I hadn't put in there `FineDiff::renderDiffToHTMLFromOpcodes`, this was a mistake, I didn't put too much thought into this, I should have realized users are going to expect a flawlessly working helper while it's not the case.

The thing to realize is that FineDiff works only on **byte-sized characters**, so in the end, only the user of the library can make sense of the diff, FineDiff can't. Diffing UTF-8 illustrates well this. 

FineDiff doesn't really try to interpret the stream of bytes, it just diff's it. My mistake was to provide a helper function to output the result in HTML, which suggests that it will always work: it's not the case. It can happen that the diff falls in the middle of a unicode character, which means it can't be rendered as HTML.

> When modifying the htmlentities call in finediff.php the codes works as expected without doing any conversion on the from and to strings

Try replacing a unicode character with another one, this is where things can break. The `mb_convert_encoding` and `htmlentities` ensure that the output will be legible, at the cost of having to render unicode characters (wholly or partially) using their ascii-based representation.

**Comment by 1emming** [comment]
@gorhill
Your answer is clear and now I understand the difficulty and sometimes impossibility for generating a good looking diff in html.
Since you've already added the option to use / hook in a custom render function for html I'll use this to add a function to deal with some exception cases in my project.
Thank you for your reply!
