### ISSUE TITLE
Temporary link for sharing does not work

### ISSUE THREAD

**Issue by mdegrees** [gorhill/PHP-FineDiff#19]
Please why temporary link does not work? it's returning 'The page you are looking for has expired' all the time, do i mess something?

Thank you in advance!

**Comment by gorhill** [comment]
It has been year since I looked at the server-side of this project. There was a huge amount of cached files (which should have been removed since a long time). So I remove all that was older than 3 months, tried and it worked from my side.

**Comment by mdegrees** [comment]
Thank you for your quick reply!

Oddly i was copying the tempolink rendred on the page http://www.raymondhill.net/finediff/viewdiff.php and it happens that the link value does not mach the link label. Instead of (for e.g) : 
http://www.raymondhill.net/finediff/viewdiff.php?data=db1e19d6bc9180b7d000d45e1b71c8d837a098fc

the link label is indicating:
http://www.raymondhill.net/viewdiff.php?data=db1e19d6bc9180b7d000d45e1b71c8d837a098fc

Note a missing 'finediff' in the link.

Now solved! Thank you!
