### ISSUE TITLE
Doesn't properly handles TABS

### ISSUE THREAD

**Issue by flashover** [gorhill/PHP-FineDiff#2]
When using your online demo, and pasting code with tabs, it doesn't preserve them after processing.

I haven't checked this behavior on my own installation, but I assume it will work the same.

The problem is I need the indentation with tabs to be preserved in the output.

**Comment by gorhill** [comment]
Tabs are preserved, the diff algorithm doesn't treat tabs any differently than other characters. The problem is certainly a HTML format issue. To be sure tabs are not collapsed at display time by the browser, the CSS 'white-space' property of the HTML element containing your text needs to be set to a value which dictate that white space characters will not be collapsed: 'pre' or 'pre-wrap' should cause the browser to display your tabs properly instead of collapsing them.

**Comment by flashover** [comment]
Okay that sounds neat! I don't know all of those CSS options, so this was a
learner. Anyway, I will probably try this out in a couple of weeks, as I
don't have the time to do so since I'm working on another project right
know.

I will keep you posted.

Thanks!

On Thu, Nov 24, 2011 at 8:05 PM, Raymond Hill <
reply@reply.github.com

> wrote:
> 
> pre-wrap

**Comment by gorhill** [comment]
Argh... Ok, now I realize you were talking about _my_ online demo, I had in mind that you were trying to preserve tabs elsewhere in some of your work. Sorry about that. I fixed it in the demo now, with my own suggestion of using 'pre-wrap' (I was using 'pre-line') :-)

**Comment by flashover** [comment]
"Ok, now I realize you were talking about _my_ online demo, I had in mind
that you were trying to preserve tabs elsewhere in some of your work."

Uhm, yes?! Isn't that the same thing? :-)

I've been out of this for a while, but I remember testing your online demo
with a piece of Juniper JUNOS configuration statements, and the diff-ing
worked brilliantly but the tabs were not preserved. And IIRC it was the
same thing with a checkout of your code and the same Juniper JUNOS
configurations.

But as a I said, I've been out of this for a while so things are not that
clear any more.

Cheers

On Thu, Nov 24, 2011 at 8:52 PM, Raymond Hill <
reply@reply.github.com

> wrote:
> 
> Ok, now I realize you were talking about _my_ online demo, I had in mind
> that you were trying to preserve tabs elsewhere in some of your work.
