### ISSUE TITLE
UTF-8 Help

### ISSUE THREAD

**Issue by Renobird** [gorhill/PHP-FineDiff#22]
I have 2 strings that contain HTML. I'm trying (unsuccessfully) to diff them, and then convert the result back to to HTML. I've tried the mb_convert_encoding() method, but can't seem to get things right.

Any help would be appreciated.

**Comment by gorhill** [comment]
Show me the code specific to the issue.

**Comment by Renobird** [comment]
Thanks for the quick reply.  just left the office for the day, I will post what I have tomorrow.

**Comment by Renobird** [comment]
Here's what I've been trying:

```
$from = mb_convert_encoding($oldHTML, 'HTML-ENTITIES', 'UTF-8');
$to = mb_convert_encoding($newHTML, 'HTML-ENTITIES', 'UTF-8');

$diff = new FineDiff($from, $to, FineDiff::$sentenceGranularity);
$rendered_diff = $diff->renderDiffToHTML();

echo $rendered_diff;
```

The output looks like:

```
"<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede."<del>Removed sentence.</del> "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>"
```

I've tried:

```
echo mb_convert_encoding( $rendered_diff, 'ASCII', 'HTML-ENTITIES');
```

Thanks for the help.

**Comment by Renobird** [comment]
Gah. The HTML I posted for the output got rendered in the comment. I'll post a link.

**Comment by gorhill** [comment]
I see, you are trying to _render_ the diff, this is different then to render the final string.

`FineDiff` works on binary string, it doesn't care about the content. So this means it could end up creating a diff operations which falls in the middle of html tags, and which means the diff itself can't be rendered as is as if it was valid html.

`renderDiffToHTML` treats the input strings as plain ASCII strings, and add HTML tags to highlight diff operations.

**Comment by Renobird** [comment]
That makes sense — thanks for the explanation. I was hoping there might be a trick to make it work. :)

**Comment by gorhill** [comment]
If the problem is specifically UTF-8 (rather than rendering HTML as plain text), then there is an issue opened somewhere for this. I have a solution which theoritically should work, but I did not implement it yet. I will admit I am not that motivated to do it currently -- I kind of doubt I will ever use PHP again.

**Comment by Renobird** [comment]
I wasn't sure of the exact issue initially, so the title isn't really accurate. My actual need to to be able to compare 2 pieces of HTML, and render the diff as valid HTML. Thanks for the quick replies, I'll go ahead and close this issue.
