### ISSUE TITLE
Do not work proper for line with similar text inside

### ISSUE THREAD

**Issue by yaroslavbr** [gorhill/PHP-FineDiff#29]
I have 3 old lines, added new  line(with same content), but the third is higlighted as inserted. Here is a screen - https://nimbus.everhelper.me/client/notes/share/311615/QKmbn2gGxTeyZwQPANXSIyPc35rd4bAX/

**Comment by gorhill** [comment]
It works fine, it does what it is expected to do: create a sequence of diff ops which allow to rebuild previous text  into new text.

**Comment by yaroslavbr** [comment]
oh, I see... Seems I did not fully understand the purpose of the library. And when I applied into my project I got wrong results. This was my fault. Accept my apologies for concern.
