### ISSUE TITLE
Render cyrillic

### ISSUE THREAD

**Issue by baceto90** [gorhill/PHP-FineDiff#31]
Hi guys,
its a great library, but i have problem with Rendering on cyrillic symbols.

$from_text = "Някаква кирилица";
$to_text = "Някаква кирилица, тест";

$from_text = mb_convert_encoding($from_text, 'HTML-ENTITIES', 'UTF-8');
$to_text = mb_convert_encoding($to_text, 'HTML-ENTITIES', 'UTF-8');

$diff_opcodes = FineDiff::getDiffOpcodes($from_text, $to_text, 2);
$rendered_diff = FineDiff::renderDiffToHTMLFromOpcodes($from_text, $diff_opcodes);

echo $rendered_diff

When i try to print $rendered_diff it shows me:
&#2013265933;&#2013266175;&#2013265930;&#2013265920;&#2013265930;&#2013265922;&#2013265920; &#2013265930;&#2013265928;&#2013265920;&#2013265928;&#2013265931;&#2013265928;&#2013266166;&#2013265920;, &#2013265922;&#2013265925;&#2013265921;&#2013265922;

&#2013265933; => &.#.2.0.1.3.2.6.5.9.3.3; (without points)
Whats wrong with it?

I tested here http://www.raymondhill.net/finediff/viewdiff-ex.php and works great...

**Comment by gorhill** [comment]
It works on bytes, not on characters.

See #11.

**Comment by baceto90** [comment]
Thanks for the replay. I saw this topic, but the downloading patch link is not available and i don't know how to integrated myself...
